stdbuf -i0 -o0 -e0 python main.py JOINTP &&
stdbuf -i0 -o0 -e0 python main.py RR &&
stdbuf -i0 -o0 -e0 python main.py PROJS &&
stdbuf -i0 -o0 -e0 python baseline.py PROJS &&
stdbuf -i0 -o0 -e0 python main.py PROJT &&
stdbuf -i0 -o0 -e0 python baseline.py PROJT &&
stdbuf -i0 -o0 -e0 python main.py PROJP &&
stdbuf -i0 -o0 -e0 python baseline.py PROJP &&
stdbuf -i0 -o0 -e0 python main.py RR1 &&
stdbuf -i0 -o0 -e0 python main.py RR2 &&
stdbuf -i0 -o0 -e0 python main.py RR3 &&
stdbuf -i0 -o0 -e0 python main.py RR4 &&
stdbuf -i0 -o0 -e0 python main.py RR5 &&
stdbuf -i0 -o0 -e0 python main.py RR6 &&
stdbuf -i0 -o0 -e0 python main.py RR7 &&
stdbuf -i0 -o0 -e0 python main.py RR8 &&
stdbuf -i0 -o0 -e0 python main.py RR9 &&
stdbuf -i0 -o0 -e0 python main.py RR10 &&
stdbuf -i0 -o0 -e0 python baseline.py RR1 &&
stdbuf -i0 -o0 -e0 python baseline.py RR2 &&
stdbuf -i0 -o0 -e0 python baseline.py RR3 &&
stdbuf -i0 -o0 -e0 python baseline.py RR4 &&
stdbuf -i0 -o0 -e0 python baseline.py RR5 &&
stdbuf -i0 -o0 -e0 python baseline.py RR6 &&
stdbuf -i0 -o0 -e0 python baseline.py RR7 &&
stdbuf -i0 -o0 -e0 python baseline.py RR8 &&
stdbuf -i0 -o0 -e0 python baseline.py RR9 &&
stdbuf -i0 -o0 -e0 python baseline.py RR10
